// Flat config, migrated from .eslintrc when eslint 10 dropped eslintrc support
// entirely. Generated from that file, so the rule set is unchanged.
import ljharb from '@ljharb/eslint-config/flat/node/8';

export default [
  { ignores: ['build/**'] },
  ...ljharb,
  {
    linterOptions: { reportUnusedDisableDirectives: 'off' },
  },
  // Root rules from .eslintrc.
  {
    files: ['**/*.js', '**/*.mjs'],
    rules: {
      'comma-dangle': 'warn',
      'func-style': 'off',
      'id-length': 'off',
      indent: ['error', 2],
      'multiline-comment-style': 'off',
      'no-unused-vars': 'warn',
      'sort-keys': 'off',
    },
  },
  // the tape harness
  {
    files: ['test.js'],
    rules: {
      'no-magic-numbers': 'off',
      'global-require': 'off',
      'max-nested-callbacks': 'off',
    },
  },
  // mostly from node core
  {
    files: ['assert.js'],
    rules: {
      'comma-dangle': 'off',
      'no-magic-numbers': 'off',
      'no-unused-vars': 'off',
      'array-bracket-newline': 'off',
      'array-element-newline': 'off',
      'arrow-body-style': 'off',
      'arrow-parens': 'off',
      curly: 'off',
      eqeqeq: 'off',
      'func-name-matching': 'off',
      'function-call-argument-newline': 'off',
      'function-paren-newline': 'off',
      'global-require': 'off',
      indent: 'off',
      'max-lines': 'off',
      'max-params': 'off',
      'new-cap': 'off',
      'no-mixed-operators': 'off',
      'no-multi-assign': 'off',
      'no-negated-condition': 'off',
      'no-param-reassign': 'off',
      'operator-linebreak': ['error', 'after'],
      'no-prototype-builtins': 'off',
      'no-restricted-syntax': 'off',
      'no-use-before-define': 'off',
      'no-var': 'off',
      'nonblock-statement-body-position': 'off',
      'object-curly-newline': 'off',
      'prefer-destructuring': 'off',
      'prefer-template': 'off',
      'sort-keys': 'off',
    },
  },
  // transcribed from node core
  {
    files: ['internal/**'],
    rules: {
      'comma-dangle': 'off',
      'no-magic-numbers': 'off',
      'no-unused-vars': 'off',
      'arrow-parens': 'off',
      camelcase: 'off',
      complexity: 'off',
      curly: 'off',
      'default-case': 'off',
      eqeqeq: 'off',
      'function-call-argument-newline': 'off',
      'function-paren-newline': 'off',
      'global-require': 'off',
      indent: 'off',
      'max-depth': 'off',
      'max-lines-per-function': 'off',
      'max-lines': 'off',
      'max-params': 'off',
      'max-statements': 'off',
      'no-else-return': 'off',
      'no-extra-parens': 'off',
      'no-implicit-coercion': 'off',
      'no-mixed-operators': 'off',
      'no-negated-condition': 'off',
      'no-param-reassign': 'off',
      'no-plusplus': 'off',
      'no-restricted-syntax': 'off',
      'no-shadow': 'off',
      'no-unused-expressions': 'off',
      'no-use-before-define': 'off',
      'no-var': 'off',
      'nonblock-statement-body-position': 'off',
      'object-curly-newline': 'off',
      'operator-linebreak': 'off',
      'prefer-template': 'off',
      semi: 'off',
      'space-before-function-paren': 'off',
      'wrap-regex': 'off',
    },
  },
  // test files from node core
  {
    files: ['test/**'],
    rules: {
      // eslint 10 added this rule; the one hit is `Boolean('' === false)` in
      // test-assert.js, where the expression is constant on purpose - the test
      // asserts on the source text assert.ok prints for a falsy expression.
      'no-constant-binary-expression': 'off',
      'no-magic-numbers': 'off',
      'no-unused-vars': 'off',
      'array-bracket-spacing': 'off',
      'arrow-parens': 'off',
      'comma-dangle': 'off',
      'consistent-return': 'off',
      curly: 'off',
      'default-param-last': 'off',
      eqeqeq: 'off',
      'function-call-argument-newline': 'off',
      'function-paren-newline': 'off',
      'global-require': 'off',
      indent: 'off',
      'keyword-spacing': 'off',
      'lines-around-directive': 'off',
      'max-lines-per-function': 'off',
      'new-cap': 'off',
      'no-else-return': 'off',
      'no-eval': 'off',
      'operator-linebreak': ['error', 'after'],
      'no-extra-parens': 'off',
      'no-inner-declarations': 'off',
      'no-invalid-this': 'off',
      'no-lone-blocks': 'off',
      'no-multi-spaces': 'off',
      'no-multiple-empty-lines': 'off',
      'no-new-func': 'off',
      'no-new-wrappers': 'off',
      'no-param-reassign': 'off',
      'no-plusplus': 'off',
      'no-prototype-builtins': 'off',
      'no-shadow': 'off',
      'no-sparse-arrays': 'off',
      'no-undef': 'off',
      'no-underscore-dangle': 'off',
      'no-use-before-define': 'off',
      'no-var': 'off',
      'nonblock-statement-body-position': 'off',
      'object-curly-spacing': 'off',
      'object-shorthand': 'off',
      'prefer-arrow-callback': 'off',
      'prefer-destructuring': 'off',
      'prefer-promise-reject-errors': 'off',
      'prefer-rest-params': 'off',
      'prefer-template': 'off',
      'quote-props': 'off',
      'space-before-function-paren': 'off',
      strict: 'off',
      'wrap-iife': 'off',
      'wrap-regex': 'off',
    },
  },

  // This file is configuration: its literals are rule options, not program logic.
  {
    files: ['eslint.config.mjs'],
    rules: { 'no-magic-numbers': 'off' },
  },
];
